### ISSUE TITLE
pimatic crashes after update to 0.4.1

### ISSUE THREAD

**Issue by thost96** [michbeck100/pimatic-echo#30]
Hi, after updating to version 0.4.1 pimatic crashed:

```
[pimatic] Invalid config of pimatic-echo: Missing property "address,mac"
```

```
13:33:04.283 [pimatic] An uncaught exception occurred: Error: listen EADDRINUSE :::12002
13:33:04.283 [pimatic]>    at Object.exports._errnoException (util.js:907:11)
13:33:04.283 [pimatic]>    at exports._exceptionWithHostPort (util.js:930:20)
13:33:04.283 [pimatic]>    at Server._listen2 (net.js:1253:14)
13:33:04.283 [pimatic]>    at listen (net.js:1289:10)
13:33:04.283 [pimatic]>    at Server.listen (net.js:1385:5)
13:33:04.283 [pimatic]>    at EventEmitter.listen (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/application.js:618:24)
13:33:04.283 [pimatic]>    at /home/pi/pimatic-app/node_modules/pimatic-echo/lib/wemo.coffee:140:18
13:33:04.283 [pimatic]>    at /home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/lodash/lodash.js:4944:15
13:33:04.283 [pimatic]>    at baseForOwn (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/lodash/lodash.js:3001:24)
13:33:04.283 [pimatic]>    at Function.forOwn (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/lodash/lodash.js:13002:24)
13:33:04.283 [pimatic]>    at Wemo.start (/home/pi/pimatic-app/node_modules/pimatic-echo/lib/wemo.coffee:139:9)
13:33:04.283 [pimatic]>    at EchoPlugin._startEmulator (/home/pi/pimatic-app/node_modules/pimatic-echo/echo.coffee:143:13)
13:33:04.283 [pimatic]>    at Framework.<anonymous> (/home/pi/pimatic-app/node_modules/pimatic-echo/echo.coffee:57:10)
13:33:04.283 [pimatic]>    at Framework.g (events.js:260:16)
13:33:04.283 [pimatic]>    at emitOne (events.js:82:20)
13:33:04.283 [pimatic]>    at Framework.emit (events.js:169:7)
13:33:04.283 [pimatic]>    at /home/pi/pimatic-app/node_modules/pimatic/lib/framework.coffee:948:12
13:33:04.283 [pimatic]>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/util.js:16:23)
13:33:04.283 [pimatic]>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:512:31)
13:33:04.283 [pimatic]>    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:569:18)
13:33:04.283 [pimatic]>    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:614:10)
13:33:04.283 [pimatic]>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:693:18)
13:33:04.283 [pimatic]>    at Promise._fulfill (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:638:18)
13:33:04.283 [pimatic]>    at Promise._resolveCallback (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:432:57)
13:33:04.283 [pimatic]>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:524:17)
13:33:04.283 [pimatic]>    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:569:18)
13:33:04.283 [pimatic]>    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:614:10)
13:33:04.283 [pimatic]>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:693:18)
13:33:04.283 [pimatic]>    at Promise._fulfill (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:638:18)
13:33:04.283 [pimatic]>    at PromiseArray._resolve (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise_array.js:126:19)
13:33:04.283 [pimatic]>    at PromiseArray._promiseFulfilled (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise_array.js:144:14)
13:33:04.283 [pimatic]>    at Promise._settlePromise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:574:26)
13:33:04.283 [pimatic]>    at Promise._settlePromise0 (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:614:10)
13:33:04.283 [pimatic]>    at Promise._settlePromises (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:693:18)
13:33:04.283 [pimatic]>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:133:16)
13:33:04.283 [pimatic]>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:143:10)
13:33:04.283 [pimatic]>    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/async.js:17:14)
13:33:04.283 [pimatic]>    at processImmediate [as _immediateCallback] (timers.js:396:17)
13:33:04.283 [pimatic]> This is most probably a bug in pimatic or in a module, please report it!
13:33:04.297 [pimatic] exiting...
```

Also adding the `address` and `mac` property doesn't help. Would be nice, if these were added automatically.

**Comment by michbeck100** [comment]
They are added automatically. It’s just a fallback if the automatic doesn’t work. It seems that the port 12000 is already in use on your system. You could either stop the process that’s using port 12000 or change the port in the pimatic-echo sources. Just search for 12000 in echo.coffee

**Comment by michbeck100** [comment]
This will configurable wit #31

**Comment by thost96** [comment]
I already checked if a service is using that port, but there isn't one. 
So i noticed that the problem is caused by two button-devices (WakeOnLanDevice), which have the same button's name WakeUp (the button's id is different) and pimatic-echo tries to publish them to my echo on the same port. This is logged to the pimatic-daemon.log file like: 

`[pimatic-echo] info: started wemo emulator for device WakeUp on port 12001`

**Comment by michbeck100** [comment]
Then please rename them for now. I will have a look into this

**Comment by michbeck100** [comment]
Could you test if the change from  7c9d656 works for you?

**Comment by thost96** [comment]
Looks like it now works fine. Thank's for the fast fix.

**Comment by michbeck100** [comment]
Included in 0.4.2

**Comment by michbeck100** [comment]
I will have to revert the changes from this issue, because they seem to be the reason for #32. So please don't update to the next version pimatic-echo until this issue is fixed.

**Comment by michbeck100** [comment]
So version 0.4.4 is not for you. I will have to check if i find another solution for your problem.

**Comment by michbeck100** [comment]
The next release will switch back to hue lights emulation only. It seems that WeMo switches are not working properly
