### ISSUE TITLE
Error: group 0 not supported

### ISSUE THREAD

**Issue by heiko1988** [michbeck100/pimatic-echo#47]
Hi,

habe mein altes Problem behoben bekommen, habe wie gesagt Port 80 freigemacht.

Danach konnte ich Geräte finden und schalten. jetzt habe ich weitere Geräte hinzugefügt, pimatic neugestartet und bekomme jetzt in der Konsole folgenden Fehler.

```
Error: group 0 not supported
    at /home/pi/pimatic-app/node_modules/pimatic-echo/lib/hue.coffee:271:15
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/layer.js:95:5)
    at /home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:281:22
    at param (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:354:14)
    at param (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:410:3)
    at next (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:275:10)
    at /home/pi/pimatic-app/node_modules/pimatic-echo/echo.coffee:129:11
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/body-parser/lib/types/json.js:109:7)
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:275:10)
    at jsonParser (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/body-parser/lib/types/json.js:109:7)
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:275:10)
    at query (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/middleware/query.js:45:5)
    at Layer.handle [as handle_request] (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:317:13)
    at /home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:335:12)
    at next (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/router/index.js:174:3)
    at EventEmitter.handle (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/application.js:174:10)
    at Server.app (/home/pi/pimatic-app/node_modules/pimatic-echo/node_modules/express/lib/express.js:39:9)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:536:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)

```

**Comment by michbeck100** [comment]
Da kannst du mal den aktuellen Stand von Github probieren. Da ist das Problem behoben.

**Comment by heiko1988** [comment]
ok, werde ich gleich mal updaten.

PS: warst ja sau schnell jetzt :)

**Comment by heiko1988** [comment]
jetzt kommt keine Fehlermeldung mehr, aber dafür findet Alexa keine Geräte mehr

**Comment by michbeck100** [comment]
Was für ein Echo nutzt du?

**Comment by heiko1988** [comment]
Einen Echo Dot 2 Gen

```
11:50:40.724 [pimatic-echo] Request: /api/xxxxxxxxxxxxxxxxxxxxxxxxx/lights
11:50:40.726 [pimatic-echo] GET Request to /api/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/lights
11:50:40.728 [pimatic-echo] Headers: {
11:50:40.728 [pimatic-echo]>  "host": "192.168.0.25",
11:50:40.728 [pimatic-echo]>  "accept": "*/*"
11:50:40.728 [pimatic-echo]>}
11:50:40.739 [pimatic-echo] Request: /api/xxxxxxxxxxxxxxxxxxxxxxxx/lights
11:50:40.742 [pimatic-echo] GET Request to /api/xxxxxxxxxxxxxxxxxxxxxxxxxx/lights
11:50:40.744 [pimatic-echo] Headers: {
11:50:40.744 [pimatic-echo]>  "host": "192.168.0.25",
11:50:40.744 [pimatic-echo]>  "accept": "*/*"
11:50:40.744 [pimatic-echo]>}
```

ich weiß nicht in wie fern die xxxxxxxxxxxxxx auf mich verfolgbar ist, darum habe ich das durch xxxxxx ersetzt

**Comment by michbeck100** [comment]
Den Discover Devices Modus in pimatic hast du aber eingeschaltet beim Scannen?

**Comment by heiko1988** [comment]
ja ich gehe auf Geräte, und dann oben rechts auf suchen.
dann gehe ich direkt auf die alexa Seite und lasse auch suchen.

Bekomme nach 20 sek auch die Meldung das der Pairing Modus wieder deaktiviert wurde.

**Comment by michbeck100** [comment]
ok, dann liegt es daran schonmal nicht. Kannst du bitte posten was unter /api/xxxxxxxxxxxxxxxxxxxxxxxxxxxxx/lights angezeigt wird?

**Comment by heiko1988** [comment]
den log habe ich direkt nicht mehr, 
habe aber jetzt nochmal eine suche gemacht und das ist dabei rausgekommen.

`12:28:21.442 [pimatic-echo] << server got: M-SEARCH * HTTP/1.1
12:28:21.442 [pimatic-echo]>HOST: 239.255.255.250:1900
12:28:21.442 [pimatic-echo]>MAN: "ssdp:discover"
12:28:21.442 [pimatic-echo]>MX: 15
12:28:21.442 [pimatic-echo]>ST: urn:schemas-upnp-org:device:basic:1
12:28:21.442 [pimatic-echo]>
12:28:21.442 [pimatic-echo]> from 192.168.0.24:50000
12:28:21.447 [pimatic-echo] >> sent response ssdp discovery response: HTTP/1.1 200 OK
12:28:21.447 [pimatic-echo]>HOST: 239.255.255.250:1900
12:28:21.447 [pimatic-echo]>EXT:
12:28:21.447 [pimatic-echo]>CACHE-CONTROL: max-age=100
12:28:21.447 [pimatic-echo]>LOCATION: http://192.168.0.25:80/description.xml
12:28:21.447 [pimatic-echo]>SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
12:28:21.447 [pimatic-echo]>hue-bridgeid: B827EBFFFEFAD076
12:28:21.447 [pimatic-echo]>ST: upnp:rootdevice
12:28:21.447 [pimatic-echo]>USN: uuid:2f402f80-da50-11e1-9b23-b827ebfad076::upnp:rootdevice
12:28:21.447 [pimatic-echo]>
12:28:21.447 [pimatic-echo]>
12:28:21.452 [pimatic-echo] >> sent response ssdp discovery response: HTTP/1.1 200 OK
12:28:21.452 [pimatic-echo]>HOST: 239.255.255.250:1900
12:28:21.452 [pimatic-echo]>EXT:
12:28:21.452 [pimatic-echo]>CACHE-CONTROL: max-age=100
12:28:21.452 [pimatic-echo]>LOCATION: http://192.168.0.25:80/description.xml
12:28:21.452 [pimatic-echo]>SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
12:28:21.452 [pimatic-echo]>hue-bridgeid: B827EBFFFEFAD076
12:28:21.452 [pimatic-echo]>ST: urn:schemas-upnp-org:device:basic:1
12:28:21.452 [pimatic-echo]>USN: uuid:2f402f80-da50-11e1-9b23-b827ebfad076::upnp:rootdevice
12:28:21.452 [pimatic-echo]>
12:28:21.452 [pimatic-echo]>
12:28:21.458 [pimatic-echo] >> sent response ssdp discovery response: HTTP/1.1 200 OK
12:28:21.458 [pimatic-echo]>HOST: 239.255.255.250:1900
12:28:21.458 [pimatic-echo]>EXT:
12:28:21.458 [pimatic-echo]>CACHE-CONTROL: max-age=100
12:28:21.458 [pimatic-echo]>LOCATION: http://192.168.0.25:80/description.xml
12:28:21.458 [pimatic-echo]>SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
12:28:21.458 [pimatic-echo]>hue-bridgeid: B827EBFFFEFAD076
12:28:21.458 [pimatic-echo]>ST: uuid: 2f402f80-da50-11e1-9b23-b827ebfad076
12:28:21.458 [pimatic-echo]>USN: uuid:2f402f80-da50-11e1-9b23-b827ebfad076::upnp:rootdevice
12:28:21.458 [pimatic-echo]>
12:28:21.458 [pimatic-echo]>
12:28:21.464 [pimatic-echo] complete sending all responses.
12:28:21.541 [pimatic-echo] << server got: M-SEARCH * HTTP/1.1
12:28:21.541 [pimatic-echo]>HOST: 239.255.255.250:1900
12:28:21.541 [pimatic-echo]>MAN: "ssdp:discover"
12:28:21.541 [pimatic-echo]>MX: 15
12:28:21.541 [pimatic-echo]>ST: urn:schemas-upnp-org:device:basic:1
12:28:21.541 [pimatic-echo]>
12:28:21.541 [pimatic-echo]> from 192.168.0.24:50000
12:28:21.546 [pimatic-echo] >> sent response ssdp discovery response: HTTP/1.1 200 OK
12:28:21.546 [pimatic-echo]>HOST: 239.255.255.250:1900
12:28:21.546 [pimatic-echo]>EXT:
12:28:21.546 [pimatic-echo]>CACHE-CONTROL: max-age=100
12:28:21.546 [pimatic-echo]>LOCATION: http://192.168.0.25:80/description.xml
12:28:21.546 [pimatic-echo]>SERVER: FreeRTOS/7.4.2, UPnP/1.0, IpBridge/1.19.0
12:28:21.546 [pimatic-echo]>hue-bridgeid: B827EBFFFEFAD076
12:28:21.546 [pimatic-echo]>ST: upnp:rootdevice
12:28:21.546 [pimatic-echo]>USN: uuid:2f402f80-da50-11e1-9b23-b827ebfad076::upnp:rootdevice
12:28:21.546 [pimatic-echo]>
`


`
12:28:27.899 [pimatic-echo] Request: /api/r1Oh6adaho8thnV1sIz4Wu05mxcmhEd86DV5SNdA/groups/0
12:28:27.901 [pimatic-echo] GET Request to /api/r1Oh6adaho8thnV1sIz4Wu05mxcmhEd86DV5SNdA/groups/0
12:28:27.902 [pimatic-echo] Headers: {
12:28:27.902 [pimatic-echo]>  "host": "192.168.0.25",
12:28:27.902 [pimatic-echo]>  "accept": "*/*"
12:28:27.902 [pimatic-echo]>}
12:28:27.911 [pimatic-echo] Request: /api/r1Oh6adaho8thnV1sIz4Wu05mxcmhEd86DV5SNdA/groups/0
12:28:27.913 [pimatic-echo] GET Request to /api/r1Oh6adaho8thnV1sIz4Wu05mxcmhEd86DV5SNdA/groups/0
12:28:27.915 [pimatic-echo] Headers: {
12:28:27.915 [pimatic-echo]>  "host": "192.168.0.25",
12:28:27.915 [pimatic-echo]>  "accept": "*/*"
12:28:27.915 [pimatic-echo]>}
12:28:28.363 [pimatic-echo] Request: /api/r1Oh6adaho8thnV1sIz4Wu05mxcmhEd86DV5SNdA/groups/0
12:28:28.366 [pimatic-echo] GET Request to /api/r1Oh6adaho8thnV1sIz4Wu05mxcmhEd86DV5SNdA/groups/0
12:28:28.369 [pimatic-echo] Headers: {
12:28:28.369 [pimatic-echo]>  "host": "192.168.0.25",
12:28:28.369 [pimatic-echo]>  "accept": "*/*"
12:28:28.369 [pimatic-echo]>}
12:28:28.501 [pimatic-echo] Request: /api/r1Oh6adaho8thnV1sIz4Wu05mxcmhEd86DV5SNdA/groups/0
12:28:28.504 [pimatic-echo] GET Request to /api/r1Oh6adaho8thnV1sIz4Wu05mxcmhEd86DV5SNdA/groups/0
12:28:28.506 [pimatic-echo] Headers: {
12:28:28.506 [pimatic-echo]>  "host": "192.168.0.25",
12:28:28.506 [pimatic-echo]>  "accept": "*/*"
12:28:28.506 [pimatic-echo]>}
12:28:31.749 [pimatic] pimatic-echo: Pairing mode is disabled again.
`

**Comment by michbeck100** [comment]
http://192.168.0.25:80/api/r1Oh6adaho8thnV1sIz4Wu05mxcmhEd86DV5SNdA/lights wäre interressant

**Comment by michbeck100** [comment]
Nächstes Mal bitte so formatiert wie es auch in pimatic angezeigt wird ;-). Sieht erstmal gut aus. Ich sehe du hast mehr als 50 Geräte registriert. Ist das wirklich notwendig? Ich würde als erstes Mal alle Geräte auf active = false setzen und dann mit einem einzelnen Gerät testen

**Comment by michbeck100** [comment]
Ausserdem fällt mir auf dass manche Geräte doppelt auftauchen. Das sollte nicht sein, der "name" muss schon eindeutig sein, sonst weiss Alexa nicht was sie schalten soll

**Comment by heiko1988** [comment]
habe es copy paste gemacht, habe es jetzt als qoute eingefügt. werde es überarbeiten. und nochmal prüfen

**Comment by heiko1988** [comment]
ich glaube das die doppelt sind, wenn ich additionalNames vergebe.

Beispiel:
Device name: Katze Brunnen 
additionalNames : Katzen Brunnen

**Comment by michbeck100** [comment]
Einfach mit ```json anfangen und ```aufhören. Siehe https://guides.github.com/features/mastering-markdown/#syntax

**Comment by heiko1988** [comment]
habe ich gemacht :)

**Comment by heiko1988** [comment]
So,

habe alle additionalNames gelöscht, pimatic neustart gemacht und was soll ich sagen alexa findet die Geräte wider und lässt sich wunderbar schalten :)

Kann man da was machen oder muss ich über alexa die namen dann vergeben, als alternative?

Danke für deine Hilfe :)

**Comment by michbeck100** [comment]
Du solltest nur keine doppelten Namen verwenden. Dann weiss Alexa eben nicht was sie tun soll. Offensichtlich reagiert sie auch schon beim Scannen allergisch auf sowas.

**Comment by heiko1988** [comment]
ok, 
aber alexa erkennt das dann offensichtlich als 2 Geräte wenn ich einen additionalNames vergebe.
werde mir da dann in alexa selbst Gruppen erstellen und dann die dann so Namentlich vergeben.

Kann man dir eig was spenden für deine arbeit per btc?

**Comment by michbeck100** [comment]
Genau dafür ist additionalNames ja gedacht. Für jeden additionalName wird ein zusätzliches Gerät in Alexa angezeigt. Der Name muss aber eben eindeutig über alle Geräte sein. 

Spenden darfst du gerne: https://www.paypal.me/michaelkotten

**Comment by heiko1988** [comment]
ok.

jetzt habe ich das auch verstanden :)

habe kein Paypal... nur bitcoin oder skrill kann ich dir anbieten zum spenden :)

**Comment by michbeck100** [comment]
Hab gerade mal ein bitcoin Konto angelegt. Wenn ich das richtig verstehe, kannst du mir damit was spenden: 1Dq1PF3AcEydtJx8GUGJJCKXXjuHaR7QBh

Danke!

**Comment by heiko1988** [comment]
Genau Richtig
Hat zwar a weng gedauert habe dir aber  jetzt eine Kleinigkeit von 20€ geschickt.

PS: Das Plugin Läuft jetzt Wider richtig Gut, besonders gefällt mir Das ich die Max Heizung damit steuern kann :)
